services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins_master
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    volumes:
      - ./jenkins_master:/var/jenkins_home

  jenkins-agent:
    image: jenkins/ssh-agent:latest-jdk21
    container_name: jenkins_agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD0EL7OSz0CzV71xBKhtX7sT0heAbFk34pfbG9/+DmZi1UJ6N2FRSkQ3DUJykdwTRW/PZxG9VYJR6m7hsfphuWfYvJ6QQgsdEexdRUM4OXc1E495CieH7qQJFRKm0KuVw5AlvAjPxAoS+fN+Vaaiar0B0LOvIUbaQONuHtv7BCEbV0blQdFjdjo2zQivj/QiyoKjQo9BhjAvhU431LJ9VI6h/syWQl9K0NNQ2ikCXfV7CHcFBgIQdaFFwXTbo+n+vBiFcnWZicsWNGHNNI8+5FxsqwhezPiivClZDNNLh9xPoS1JsyYkzgKn9GXFRjL5vN1FcHPVN5y2ciPzaIAWCwl1uPwT+WbZFK4Mx/AdVkf6OlFTE8mXR+XRsaO9+5ahvt9CwlzG+VKC9LAHuY33s7a75p6oHSi/u8xEG+vl7OKMi8QiYtbG6g44lH+1zErJw7VOi1uVGjSqsWjFK8kaEKLdu0WlMITWSCd9BOnjXNRE6bonNEmQqOfGM2mTOy0iU= jenkins@bcb55ee88c98
    networks:
      - jenkins-network
    volumes:
      - ./jenkins_agent:/home/jenkins/agent
networks:
  jenkins-network:
    driver: bridge
  