server:
  port: 8903
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage-manager
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop